version: "3.8"

services:
  #Это конфигурация Docker Compose для службы базы данных MongoDB.
  mongodb:
    container_name: mongodb
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    env_file: mongodb.env
    image: bitnami/mongodb:latest
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"
    shm_size: 256mb
    volumes:
      - "/mnt/docker-volumes/db/mongodb/data:/data/db"

networks:
  external:
    external: true
    name: $NETWORK
